TZ: 'Australia/Sydney'
INIT_PACKAGES: [ 'bash', 'curl', 'wget', 'grep', 'git', 'ufw', 'net-tools', 'unattended-upgrades']

# Pihole task variables
PIHOLE_BIN_PATH: /usr/local/bin/pihole
PIHOLE_GROUP: pihole
PIHOLE_USER: pihole
PIHOLE_ETC_DIR: /etc/pihole/
PIHOLE_UPDATE: true
PIHOLE_REINSTALL: false

# Pivpn task variables
PIVPN_BIN_PATH: /usr/local/bin/pivpn
PIVPN_GROUP: pivpn
PIVPN_USER: pivpn
PIVPN_ETC_DIR: /etc/pivpn/
PIVPN_UPDATE: true
PIVPN_REINSTALL: false

## ================================================
## PI-HOLE CONFIGURATION
## https://docs.pi-hole.net/ftldns/configfile/
## ================================================

## echo -n P@ssw0rd | sha256sum | awk '{printf "%s",$1 }' | sha256sum
PIHOLE_WEBPASSWORD: 344d7c64abf96d9a522e7b00a872a667ad2c1a769b6e71449a803b4e2f107716

## DNS Configuration
PIHOLE_DNS_FQDN_REQUIRED: "true"
PIHOLE_DNS_BOGUS_PRIV: "true"
PIHOLE_DNSSEC: "true"
PIHOLE_DNSMASQ_LISTENING: "single"

## Conditional Forwarding
PIHOLE_CONDITIONAL_FORWARDING: "false"
PIHOLE_CONDITIONAL_FORWARDING_IP:
PIHOLE_CONDITIONAL_FORWARDING_DOMAIN:
PIHOLE_CONDITIONAL_FORWARDING_REVERSE:

## Rev Server
PIHOLE_REV_SERVER: "false"
PIHOLE_REV_SERVER_CIDR:
PIHOLE_REV_SERVER_TARGET:
PIHOLE_REV_SERVER_DOMAIN:

PIHOLE_INTERFACE: "local-service"
PIHOLE_IPV4_ADDRESS: 192.168.3.5
PIHOLE_IPV6_ADDRESS:
PIHOLE_DNS_1: 192.168.3.1
PIHOLE_DNS_2: 192.168.3.1
PIHOLE_QUERY_LOGGING: "true"
PIHOLE_INSTALL_WEB_SERVER: "true"
PIHOLE_INSTALL_WEB_INTERFACE: "true"
PIHOLE_LIGHTTPD_ENABLED: "true"
PIHOLE_ADMIN_EMAIL: ian@teda.id.au
PIHOLE_WEBLAYOUT: "boxed"
PIHOLE_WEBTHEME: "default-light"
PIHOLE_BLOCKING_ENABLED: "true"


## ================================================
## PIVPN CONFIGURATION
## https://docs.pivpn.io/install/
## ================================================

PIVPN_USER_PASSWORD: "pivpn"
PIVPN_UNATTENDED_UPGRADES_PACKAGE: "unattended-upgrades"
PIVPN_NETWORK_INTERFACE: "eth0"
PIVPN_IPV4_DNS: "localhost"
PIVPN_IPV4_ADDRESS: "{{ ansible_default_ipv4.address if ansible_default_ipv4.address is defined else '' }}"
PIVPN_IPV4_GATEWAY: "{{ ansible_default_ipv4.gateway if ansible_default_ipv4.gateway is defined else '' }}"
PIVPN_PROTOCOL: "udp"
PIVPN_PORT: "1194"
PIVPN_ENCRYPTION_KEY_SIZE: "256"
PIVPN_ENABLE_OPENVPN24: "true"
PIVPN_DOWNLOAD_DH_PARAM: "false"
PIVPN_PUBLIC_SERVER_NAME: ""
PIVPN_DNS_SERVER1: "{{ ansible_dns.nameservers[0] if ansible_dns.nameservers|length>=1 else '' }}"
PIVPN_DNS_SERVER2: "{{ ansible_dns.nameservers[1] if ansible_dns.nameservers|length>=2 else '' }}"
PIVPN_SERVER_NAME: "{{ hostname }}"