## ======================================
## CONFIGURE RASPBERRY PI
## Configure raspberry pi OS
## ======================================

- name: Suspend default pi account
  ansible.builtin.user:
    name: pi
    state: present
    password: '!'  # '!' Suspends Linux accounts
    
- name: Set hostname {{ hostname }} in /etc/hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
  notify: pihole reboot
    
- name: Set hosts {{ hostname }} to /etc/hosts
  ansible.builtin.lineinfile:
    path: '/etc/hosts'
    state: present
    regexp: '^127\.0\.0\.1[ \t]+localhost'
    line: '127.0.0.1 localhost {{ hostname }}'
  notify: pihole reboot

- name: Set time zone for {{ hostname }}
  community.general.timezone:
    name: "{{ TZ }}"