- name: Bootstrap {{ ansible_user }}
  import_tasks: ansible_user.yaml

- name: Configure raspberry pi OS
  import_tasks: config.yaml

- name: Add initial software packages
  import_tasks: packages.yaml

- name: Harden sshd
  import_tasks: sshd.yaml

- name: Setup firewall
  import_tasks: firewall.yaml

- name: Mount usb-local
  import_tasks: usb-local.yaml