# ==============================================
# INITIAL PACKAGES
# Update OS and install initial OS packages
# ==============================================

- name: Upgrade OS (apt-get dist-upgrade)
  tags: packages
  ansible.builtin.apt:
    force_apt_get: yes
    update_cache: yes
    autoclean: yes
    autoremove: yes
    upgrade: dist

- name: Install required packages
  tags: packages
  ansible.builtin.apt: 
    name: "{{ INIT_PACKAGES }}"
    state: latest
    autoclean: yes
    autoremove: yes

- name: Remove dependencies that are no longer required
  tags: packages
  ansible.builtin.apt:
    autoremove: yes

- name: Check if reboot is needed
  tags: packages
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot
  tags: packages
  reboot:
  when: reboot_required.stat.exists